package com.example.capstoneproject.model

object DataSourceUser {
    var user = listOf(
        DataUser(
            "hadiseptian",
            "",
            1,
            "a269bsy2325@bangkit.academy",
            "nursukamto",
            "hadi12345",
            "gold"
        ),
        DataUser(
            "dinda",
            "08115582588",
            2,
            "dindhana12@gmail.com",
            "afifah",
            "dinda12345",
            "none"
        ),
        DataUser(
            "muchlis",
            "081350502003",
            3,
            "a269bsy2847@gmail.com",
            "abimanyu",
            "muchlis12345",
            "bronze"
        ),
        DataUser(
            "account",
            "081234567890",
            4,
            "test@gmail.com",
            "test",
            "12345678",
            "none"
        ),
        DataUser(
            "John",
            "08125519352",
            1701,
            "john@gmail.com",
            "Doe",
            "12345678",
            "silver"
        )
    )
}